site_name: Liu's Excerpt
theme:
  name: 'material'
  palette:
    primary: teal
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.critic
    - pymdownx.tasklist
    - admonition
    - footnotes
    - pymdownx.emoji
    - pymdownx.details
    - pymdownx.highlight
nav:
  - Home: index.md
  - 「三国演义」:
    - "桃园三结义": sgyy-01.md